// apps/nuxt-app/pages/admin/users/[id]/index.vue
<template>
  <div class="container mx-auto py-10 px-5">
    <!-- Back link -->
    <div class="flex items-center mb-6">
      <NuxtLink to="/admin/users" class="text-primary hover:text-primary/80">
        ← {{ t('actions.backToList') }}
      </NuxtLink>
    </div>

    <!-- Page title -->
    <h1 class="text-3xl font-bold mb-6">
      {{ isEditMode ? t('admin.users.editUser') : t('admin.users.createUser') }}
    </h1>

    <!-- Error message -->
    <div v-if="errorMessage" class="mb-4 p-4 text-destructive bg-destructive/10 rounded-md">
      {{ errorMessage }}
    </div>

    <!-- Loading skeleton -->
    <div v-if="pending" class="max-w-2xl mx-auto">
      <Card>
        <CardHeader>
          <Skeleton class="h-7 w-40 mb-2" />
          <Skeleton class="h-4 w-60" />
        </CardHeader>
        <CardContent class="space-y-4">
          <div v-for="i in 6" :key="i" class="space-y-2">
            <Skeleton class="h-5 w-24" />
            <Skeleton class="h-10 w-full" />
          </div>
        </CardContent>
        <CardFooter class="pt-6">
          <Skeleton class="h-10 w-32" />
        </CardFooter>
      </Card>
    </div>

    <!-- Form -->
    <form v-else @submit="onSubmit" class="max-w-2xl mx-auto">
      <Card>
        <CardHeader>
          <CardTitle>{{ t('admin.users.form.title') }}</CardTitle>
          <CardDescription>{{ t('admin.users.form.description') }}</CardDescription>
        </CardHeader>
        <CardContent class="space-y-4">
          <!-- Name field -->
          <div class="space-y-2">
            <Label for="name">{{ t('admin.users.form.labels.name') }}</Label>
            <Input 
              id="name"
              v-bind="nameAttrs"
              v-model="name"
              :placeholder="t('admin.users.form.placeholders.name')"
              :class="errors.name ? 'border-destructive' : ''"
            />
            <p v-if="errors.name" class="text-destructive text-sm">{{ errors.name }}</p>
          </div>
          
          <!-- Email field -->
          <div class="space-y-2">
            <Label for="email">{{ t('admin.users.form.labels.email') }}</Label>
            <Input 
              id="email"
              type="email"
              v-bind="emailAttrs"
              v-model="email"
              :disabled="isEditMode"
              :placeholder="t('admin.users.form.placeholders.email')"
              :class="errors.email ? 'border-destructive' : ''"
            />
            <p v-if="errors.email" class="text-destructive text-sm">{{ errors.email }}</p>
          </div>
          
          <!-- Password field (only for new users) -->
          <div v-if="!isEditMode" class="space-y-2">
            <Label for="password">{{ t('admin.users.form.labels.password') }}</Label>
            <Input 
              id="password"
              type="password"
              v-bind="passwordAttrs"
              v-model="password"
              :placeholder="t('admin.users.form.placeholders.password')"
              :class="errors.password ? 'border-destructive' : ''"
            />
            <p v-if="errors.password" class="text-destructive text-sm">{{ errors.password }}</p>
          </div>
          
          <!-- Role field -->
          <div class="space-y-2">
            <Label for="role">{{ t('admin.users.form.labels.role') }}</Label>
            <Select v-model="role">
              <SelectTrigger :class="errors.role ? 'border-destructive' : ''">
                <SelectValue :placeholder="t('admin.users.form.placeholders.selectRole')" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="admin">{{ t('dashboard.roles.admin') }}</SelectItem>
                <SelectItem value="user">{{ t('dashboard.roles.user') }}</SelectItem>
              </SelectContent>
            </Select>
            <p v-if="errors.role" class="text-destructive text-sm">{{ errors.role }}</p>
          </div>
          
          <!-- Image field -->
          <div class="space-y-2">
            <Label for="image">{{ t('admin.users.form.labels.image') }}</Label>
            <Input 
              id="image"
              v-bind="imageAttrs"
              v-model="image"
              :placeholder="t('admin.users.form.placeholders.image')"
              :class="errors.image ? 'border-destructive' : ''"
            />
            <p v-if="errors.image" class="text-destructive text-sm">{{ errors.image }}</p>
          </div>

          <!-- Phone number field -->
          <div class="space-y-2">
            <Label for="phoneNumber">{{ t('admin.users.form.labels.phoneNumber') }}</Label>
            <Input 
              id="phoneNumber"
              v-bind="phoneNumberAttrs"
              v-model="phoneNumber"
              :placeholder="t('admin.users.form.placeholders.phoneNumber')"
              :class="errors.phoneNumber ? 'border-destructive' : ''"
            />
            <p v-if="errors.phoneNumber" class="text-destructive text-sm">{{ errors.phoneNumber }}</p>
          </div>

          <!-- Email verified toggle -->
          <div class="flex items-center justify-between">
            <Label for="emailVerified" class="font-semibold">
              {{ t('admin.users.form.labels.emailVerified') }}
            </Label>
            <Switch v-model="emailVerified" />
          </div>

          <!-- Phone verified toggle -->
          <div class="flex items-center justify-between">
            <Label for="phoneNumberVerified" class="font-semibold">
              {{ t('admin.users.form.labels.phoneVerified') }}
            </Label>
            <Switch v-model="phoneNumberVerified" />
          </div>

          <!-- Banned toggle -->
          <div class="flex items-center justify-between">
            <Label for="banned" class="font-semibold">
              {{ t('admin.users.form.labels.banned') }}
            </Label>
            <Switch v-model="banned" />
          </div>
          
          <!-- Ban reason field -->
          <div class="space-y-2">
            <Label for="banReason">{{ t('admin.users.form.labels.banReason') }}</Label>
            <Input 
              id="banReason"
              v-bind="banReasonAttrs"
              v-model="banReason"
              :placeholder="t('admin.users.form.placeholders.banReason')"
              :class="errors.banReason ? 'border-destructive' : ''"
            />
            <p v-if="errors.banReason" class="text-destructive text-sm">{{ errors.banReason }}</p>
          </div>
        </CardContent>
        <CardFooter class="flex justify-between space-x-4 pt-6">
          <div class="flex space-x-4">
            <Button 
              type="submit" 
              :disabled="isSubmitting"
              class="flex items-center gap-2"
            >
              <Save class="h-4 w-4" />
              {{ isSubmitting ? t('common.loading') : (isEditMode ? t('actions.saveChanges') : t('actions.createUser')) }}
            </Button>
            
            <!-- Delete button (only for edit mode) -->
            <AlertDialog v-if="isEditMode">
              <AlertDialogTrigger as-child>
                <Button variant="destructive" type="button" class="flex items-center gap-2">
                  <Trash2 class="h-4 w-4" />
                  {{ t('actions.deleteUser') }}
                </Button>
              </AlertDialogTrigger>
              <AlertDialogContent>
                <AlertDialogHeader>
                  <AlertDialogTitle>{{ t('admin.users.deleteDialog.title') }}</AlertDialogTitle>
                  <AlertDialogDescription>
                    {{ t('admin.users.deleteDialog.description') }}
                  </AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter>
                  <AlertDialogCancel>{{ t('actions.cancel') }}</AlertDialogCancel>
                  <AlertDialogAction 
                    @click="handleDelete"
                    class="bg-destructive hover:bg-destructive/90"
                  >
                    {{ t('actions.delete') }}
                  </AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>
          </div>
        </CardFooter>
      </Card>
    </form>
  </div>
</template>

<script setup lang="ts">
import { Save, Trash2 } from 'lucide-vue-next'
import { toast } from 'vue-sonner'
import { authClientVue } from '@libs/auth/authClient'
import { createAdminUserValidators } from '@libs/validators'
import { toTypedSchema } from '@vee-validate/zod'
import { useForm } from 'vee-validate'
import type { z } from 'zod'

// Define page metadata
definePageMeta({
  layout: 'admin'
  // No middleware needed - auth.global.ts handles admin routes automatically
})

// Get route params and composables
const route = useRoute()
const router = useRouter()
const { t } = useI18n()

const userId = route.params.id as string
const isEditMode = userId !== 'new'

// Create validators with translation function
const { createAdminUserFormSchema, updateAdminUserFormSchema } = createAdminUserValidators(t)

// Choose the appropriate schema based on mode
const validationSchema = computed(() => {
  return isEditMode ? updateAdminUserFormSchema : createAdminUserFormSchema
})

// Setup form with VeeValidate
const { 
  handleSubmit, 
  errors, 
  defineField,
  setValues,
  resetForm
} = useForm({
  validationSchema: toTypedSchema(validationSchema.value)
})

// Define form fields with VeeValidate
const [name, nameAttrs] = defineField('name')
const [email, emailAttrs] = defineField('email')
const [password, passwordAttrs] = defineField('password')
const [role, roleAttrs] = defineField('role')
const [image, imageAttrs] = defineField('image')
const [phoneNumber, phoneNumberAttrs] = defineField('phoneNumber')
const [banReason, banReasonAttrs] = defineField('banReason')

// Define boolean fields separately (VeeValidate doesn't handle these well with defineField)
const emailVerified = ref(false)
const phoneNumberVerified = ref(false)
const banned = ref(false)

// Loading and error states
const pending = ref(false)
const isSubmitting = ref(false)
const errorMessage = ref('')

// Define types for API responses
interface UserData {
  id: string
  name: string
  email: string
  role: string
  image?: string | null
  phoneNumber?: string | null
  emailVerified: boolean
  phoneNumberVerified: boolean
  banned: boolean
  banReason?: string | null
}

// Fetch user data for edit mode
let userData: Ref<UserData | null> = ref(null)

if (isEditMode) {
  const { data } = await useFetch<UserData>(`/api/users/${userId}`, {
    server: false,
    onRequest() {
      pending.value = true
    },
    onResponse({ response }) {
      pending.value = false
      if (response._data) {
        const data = response._data
        // Set form values using VeeValidate
        setValues({
          name: data.name || '',
          email: data.email || '',
          role: data.role || 'user',
          image: data.image || '',
          phoneNumber: data.phoneNumber || '',
          banReason: data.banReason || ''
        })
        
        // Set boolean values separately
        emailVerified.value = data.emailVerified || false
        phoneNumberVerified.value = data.phoneNumberVerified || false
        banned.value = data.banned || false
      }
    },
    onResponseError({ error }) {
      pending.value = false
      errorMessage.value = error?.message || t('admin.users.messages.fetchError')
    }
  })
  userData = data
}

// Form submission with VeeValidate
const onSubmit = handleSubmit(async (values) => {
  isSubmitting.value = true
  errorMessage.value = ''

  try {
    // Prepare form data
    const formData = {
      ...values,
      emailVerified: emailVerified.value,
      phoneNumberVerified: phoneNumberVerified.value,
      banned: banned.value
    }

    // Debug: Log the form data being sent
    console.log('Form data being sent:', formData)

    if (isEditMode) {
      // Update all user data through single API call
      await $fetch(`/api/users/${userId}`, {
        method: 'PATCH',
        body: formData,
      })

      toast.success(t('admin.users.messages.updateSuccess'))
    } else {
      // Create user
      const { data, error } = await authClientVue.admin.createUser({
        name: formData.name,
        email: formData.email,
        password: formData.password || '',
        role: formData.role as 'admin' | 'user',
        data: {
          image: formData.image || undefined,
          phoneNumber: formData.phoneNumber || undefined,
          emailVerified: formData.emailVerified,
          phoneNumberVerified: formData.phoneNumberVerified,
          banned: formData.banned,
          banReason: formData.banReason || undefined,
        },
      })

      if (error) {
        toast.error(error.message || t('admin.users.messages.createError'))
        return
      }

      toast.success(t('admin.users.messages.createSuccess'))
    }

    // Navigate back to users list
    await router.push('/admin/users')
  } catch (error: any) {
    const message = error?.message || t('admin.users.messages.operationFailed')
    errorMessage.value = message
    toast.error(message)
  } finally {
    isSubmitting.value = false
  }
})

// Delete user
const handleDelete = async () => {
  const { data, error } = await authClientVue.admin.removeUser({
    userId,
  })
  
  if (error) {
    const message = error.message || t('admin.users.messages.deleteError')
    errorMessage.value = message
    toast.error(message)
    return
  }
  
  toast.success(t('admin.users.messages.deleteSuccess'))
  await router.push('/admin/users')
}

// Set page title
useHead({
  title: computed(() => isEditMode ? t('admin.users.editUser') : t('admin.users.createUser'))
})
</script>

// apps/next-app/src/app/admin/users/[id]/page.tsx
// "use client"

import { notFound } from 'next/navigation'
import { headers } from 'next/headers'
import { db } from '@libs/database/client'
import { user } from '@libs/database/schema/user'
import { eq } from 'drizzle-orm'
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Switch } from '@/components/ui/switch'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Label } from '@/components/ui/label'
import { userRoles } from '@libs/database/constants'
import Link from 'next/link'
import { SaveIcon, Trash2Icon } from 'lucide-react'

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog'

interface UserDetailPageProps {
  params: {
    id: string
  }
}

export default async function UserDetailPage({ params }: UserDetailPageProps) {
  // Extract user ID from URL params
  const { id } = params

  // Fetch user from database
  const users = await db.select().from(user).where(eq(user.id, id))
  
  // If user not found, return 404 page
  if (!users || users.length === 0) {
    notFound()
  }

  const userData = users[0]

  return (
    <div className="container mx-auto p-10">
      <div className="flex justify-between items-center mb-6">
        <Link href="/admin/users" className="text-blue-500 hover:text-blue-700">
          ← Back to Users
        </Link>
        
        <Button type="submit" form="user-edit-form" className="flex items-center gap-2">
          <SaveIcon className="h-4 w-4" />
          Save Changes
        </Button>
      </div>

      <h1 className="text-3xl font-bold mb-6">Edit User</h1>

      <form id="user-edit-form" action="/api/admin/users/update" method="POST" className="space-y-6">
        <input type="hidden" name="id" value={userData.id} />
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card>
            <CardHeader>
              <CardTitle>Basic Information</CardTitle>
              <CardDescription>User profile information</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="id">ID (Read-only)</Label>
                <Input id="id" value={userData.id} disabled />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="name">Name</Label>
                <Input id="name" name="name" defaultValue={userData.name} />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="email">Email (Read-only)</Label>
                <Input id="email" value={userData.email} disabled />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="role">Role</Label>
                <Select name="role" defaultValue={userData.role}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select role" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value={userRoles.ADMIN}>{userRoles.ADMIN}</SelectItem>
                    <SelectItem value={userRoles.USER}>{userRoles.USER}</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="image">Profile Image URL</Label>
                <Input id="image" name="image" defaultValue={userData.image || ''} />
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Account Status</CardTitle>
              <CardDescription>User account verification and status</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <Label htmlFor="emailVerified" className="font-semibold">Email Verified</Label>
                <Switch 
                  id="emailVerified" 
                  name="emailVerified" 
                  defaultChecked={userData.emailVerified}
                />
              </div>
              
              <div className="flex items-center justify-between">
                <Label htmlFor="banned" className="font-semibold">Banned</Label>
                <Switch 
                  id="banned" 
                  name="banned" 
                  defaultChecked={userData.banned || false}
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="banReason">Ban Reason</Label>
                <Input 
                  id="banReason" 
                  name="banReason" 
                  defaultValue={userData.banReason || ''}
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="banExpires">Ban Expires (Unix Timestamp)</Label>
                <Input 
                  id="banExpires" 
                  name="banExpires" 
                  defaultValue={userData.banExpires?.toString() || ''}
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="createdAt">Created At (Read-only)</Label>
                <Input 
                  id="createdAt" 
                  value={userData.createdAt ? new Date(userData.createdAt).toLocaleString() : 'N/A'} 
                  disabled
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="updatedAt">Updated At (Read-only)</Label>
                <Input 
                  id="updatedAt" 
                  value={userData.updatedAt ? new Date(userData.updatedAt).toLocaleString() : 'N/A'} 
                  disabled
                />
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Authentication</CardTitle>
              <CardDescription>Provider and phone verification</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="provider">Provider</Label>
                <Input id="provider" name="provider" defaultValue={userData.provider || ''} />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="providerId">Provider ID</Label>
                <Input id="providerId" name="providerId" defaultValue={userData.providerId || ''} />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="phoneNumber">Phone Number</Label>
                <Input id="phoneNumber" name="phoneNumber" defaultValue={userData.phoneNumber || ''} />
              </div>
              
              <div className="flex items-center justify-between">
                <Label htmlFor="phoneNumberVerified" className="font-semibold">Phone Verified</Label>
                <Switch 
                  id="phoneNumberVerified" 
                  name="phoneNumberVerified" 
                  defaultChecked={userData.phoneNumberVerified || false}
                />
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Actions</CardTitle>
              <CardDescription>Save or delete this user</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <Button 
                  type="submit" 
                  form="user-edit-form" 
                  className="flex items-center gap-2"
                >
                  <SaveIcon className="h-4 w-4" />
                  Save Changes
                </Button>
                
                <AlertDialog>
                  <AlertDialogTrigger asChild>
                    <Button variant="destructive" type="button" className="flex items-center gap-2">
                      <Trash2Icon className="h-4 w-4" />
                      Delete User
                    </Button>
                  </AlertDialogTrigger>
                  <AlertDialogContent>
                    <AlertDialogHeader>
                      <AlertDialogTitle>Are you absolutely sure?</AlertDialogTitle>
                      <AlertDialogDescription>
                        This action cannot be undone. This will permanently delete the user
                        and remove their data from our servers.
                      </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                      <AlertDialogCancel>Cancel</AlertDialogCancel>
                      <form action="/api/admin/users/delete" method="POST">
                        <input type="hidden" name="id" value={userData.id} />
                        <AlertDialogAction type="submit" className="bg-red-600 hover:bg-red-700">
                          Delete
                        </AlertDialogAction>
                      </form>
                    </AlertDialogFooter>
                  </AlertDialogContent>
                </AlertDialog>
              </div>
            </CardContent>
            <CardFooter className="text-sm text-gray-500">
              All changes will be logged for accountability.
            </CardFooter>
          </Card>
        </div>
      </form>
    </div>
  )
}
