// apps/next-app/app/[lang]/(root)/pricing/page.tsx
'use client';

import { config } from '@config';
import { useTranslation } from "@/hooks/use-translation";
import type { Plan } from '@config';
import { useState, useEffect } from 'react';
import { useRouter, usePathname } from 'next/navigation';
import { toast } from 'sonner';
import { authClientReact } from "@libs/auth/authClient";
import QRCode from 'qrcode';
import { motion } from "framer-motion";
import { 
  Check, 
  Star, 
  Sparkles,
  Crown,
  Zap,
  Shield,
  Heart,
  ArrowRight
} from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Steps, Step } from "@/components/ui/steps";
import { Button } from "@/components/ui/button";

export default function PricingPage() {
  const { t, locale: currentLocale } = useTranslation();
  const router = useRouter();
  const pathname = usePathname();
  const [loading, setLoading] = useState<string | null>(null);
  const [qrCodeUrl, setQrCodeUrl] = useState<string | null>(null);
  const [currentPlan, setCurrentPlan] = useState<Plan | null>(null);
  const [currentStep, setCurrentStep] = useState(0);
  const [orderId, setOrderId] = useState<string | null>(null);
  const [pollingInterval, setPollingInterval] = useState<NodeJS.Timeout | null>(null);
  
  const { data: session, isPending } = authClientReact.useSession();
  const user = session?.user;

  const plans = Object.values(config.payment.plans) as unknown as Plan[];

  // 清理轮询定时器
  useEffect(() => {
    return () => {
      if (pollingInterval) {
        clearInterval(pollingInterval);
      }
    };
  }, [pollingInterval]);

  const startPolling = (orderId: string) => {
    // 先清除可能存在的轮询
    if (pollingInterval) {
      clearInterval(pollingInterval);
    }

    const interval = setInterval(async () => {
      try {
        const response = await fetch(`/api/payment/query?orderId=${orderId}&provider=wechat`);
        const data = await response.json();

        if (data.status === 'paid') {
          clearInterval(interval);
          setPollingInterval(null);
          router.push(`/${currentLocale}/payment-success?provider=wechat`);
        } else if (data.status === 'failed') {
          clearInterval(interval);
          setPollingInterval(null);
          toast.error(t.payment.result.failed);
          closeQrCodeModal();
        }
      } catch (error) {
        console.error('Payment polling error:', error);
      }
    }, 3000); // 每3秒查询一次

    setPollingInterval(interval);
  };

  const handleSubscribe = async (plan: Plan) => {
    try {
      if (!user) {
        const returnPath = encodeURIComponent(pathname);
        router.push(`/${currentLocale}/signin?returnTo=${returnPath}`);
        return;
      }

      setLoading(plan.id);
      const provider = plan.provider || 'stripe';
      setCurrentPlan(plan);
      
      const response = await fetch('/api/payment/initiate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          planId: plan.id,
          provider
        })
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to initiate payment');
      }
      
      if (provider === 'wechat') {
        if (data.paymentUrl) {
          try {
            const qrDataUrl = await QRCode.toDataURL(data.paymentUrl);
            setQrCodeUrl(qrDataUrl);
            setOrderId(data.providerOrderId);
            setCurrentStep(1);
            startPolling(data.providerOrderId);
          } catch (err) {
            console.error('QR code generation error:', err);
            toast.error(t.common.unexpectedError);
          }
        }
      } else {
        if (data.paymentUrl) {
          window.location.href = data.paymentUrl;
        }
      }
    } catch (error) {
      console.error('Payment error:', error);
      toast.error(t.common.unexpectedError);
    } finally {
      setLoading(null);
    }
  };

  const closeQrCodeModal = () => {
    // 如果当前正在处理支付，提示用户确认是否取消
    if (currentStep < 2 && orderId) { // 还未完成支付且有订单ID
      const confirmCancel = window.confirm(t.payment.confirmCancel);
      if (!confirmCancel) {
        return; // 用户取消关闭，继续支付流程
      }
      
      // 调用关闭订单API
      fetch(`/api/payment/cancel?orderId=${orderId}&provider=wechat`, {
        method: 'POST'
      }).then(response => {
        if (response.ok) {
          toast.info(t.payment.orderCanceled);
        } else {
          console.error('Failed to cancel order');
          toast.error(t.common.unexpectedError);
        }
      }).catch(error => {
        console.error('Cancel order error:', error);
        toast.error(t.common.unexpectedError);
      });
    }
    
    setQrCodeUrl(null);
    setCurrentPlan(null);
    setCurrentStep(0);
    setOrderId(null);
    if (pollingInterval) {
      clearInterval(pollingInterval);
      setPollingInterval(null);
    }
  };

  const steps: Step[] = [
    { title: t.payment.steps.initiate, description: t.payment.steps.initiateDesc },
    { title: t.payment.steps.scan, description: t.payment.steps.scanDesc },
    { title: t.payment.steps.pay, description: t.payment.steps.payDesc },
  ];

  // 获取推荐计划
  const getRecommendedPlan = () => {
    return plans.find(plan => plan.recommended) || plans[0];
  };

  const recommendedPlan = getRecommendedPlan();

  return (
    <>
      <style jsx>{`
        .animate-blob {
          animation: blob 7s infinite;
        }
        .animation-delay-2000 {
          animation-delay: 2s;
        }
        .animation-delay-4000 {
          animation-delay: 4s;
        }
        @keyframes blob {
          0% {
            transform: translate(0px, 0px) scale(1);
          }
          33% {
            transform: translate(30px, -50px) scale(1.1);
          }
          66% {
            transform: translate(-20px, 20px) scale(0.9);
          }
          100% {
            transform: translate(0px, 0px) scale(1);
          }
        }
      `}</style>
      
      <div className="min-h-screen bg-background">
        {/* Hero Section */}
        <section className="relative py-24 sm:py-32 overflow-hidden">
          <div className="mx-auto max-w-7xl px-6 lg:px-8 relative z-10">
            <motion.div 
              className="mx-auto max-w-4xl text-center"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
            >
              <motion.div
                className="inline-flex items-center space-x-2 px-4 py-2 bg-chart-1-bg-15 rounded-full border border-chart-1/20 mb-8"
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.6, delay: 0.2 }}
              >
                <Sparkles className="h-4 w-4 text-chart-1" />
                <span className="text-xs font-medium text-chart-1">{t.pricing.title}</span>
              </motion.div>

              <h2 className="text-4xl md:text-6xl font-bold tracking-tight text-foreground mb-6">
                <span className="text-gradient-chart-warm">
            {t.pricing.subtitle}
                </span>
              </h2>
              
              <p className="text-xl text-muted-foreground max-w-3xl mx-auto leading-relaxed">
                选择最适合你的方案，开始你的 TinyShip 之旅。
                一次购买，终身使用，早鸟价仅限前 100 名用户。
          </p>
            </motion.div>
        </div>
        </section>

        {/* Pricing Cards */}
        <section className="py-24">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 lg:gap-12">
              {plans.map((plan, index) => {
            const i18n = plan.i18n && typeof plan.i18n === 'object' ? plan.i18n[currentLocale] : undefined;
                const isRecommended = plan.recommended;
                const isLifetime = plan.id === 'lifetime';
                
            return (
                  <motion.div
                key={plan.id}
                    className={`relative rounded-xl p-6 shadow-lg transition-all duration-300 hover:scale-[1.02] ${
                      isRecommended 
                        ? 'bg-card border-2 border-chart-1 shadow-chart-1/20' 
                        : 'bg-card border border-border hover:border-border/80'
                    }`}
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6, delay: index * 0.1 }}
                    viewport={{ once: true }}
                  >
                    {/* Recommended Badge */}
                    {isRecommended && (
                      <div className="absolute -top-4 left-1/2 transform -translate-x-1/2">
                        <div className="inline-flex items-center space-x-2 px-3 py-1.5 bg-gradient-chart-warm text-white rounded-full shadow-md">
                          <Crown className="h-3.5 w-3.5" />
                          <span className="text-xs font-medium">推荐选择</span>
                        </div>
                      </div>
                    )}

                    {/* Plan Header */}
                    <div className="text-center mb-6">
                      <h3 className={`text-xl font-bold mb-2 ${
                        isRecommended ? 'text-card-foreground' : 'text-foreground'
                      }`}>
                      {i18n?.name || plan.name}
                    </h3>
                      
                      <p className={`text-sm ${
                        isRecommended ? 'text-muted-foreground' : 'text-muted-foreground'
                      }`}>
                    {i18n?.description || plan.description}
                  </p>
                    </div>

                    {/* Price */}
                    <div className="text-center mb-6">
                      <div className="flex items-baseline justify-center space-x-2">
                        <span className={`text-4xl font-bold ${
                          isRecommended ? 'text-card-foreground' : 'text-foreground'
                        }`}>
                      {plan.currency === 'CNY' ? '¥' : '$'}{plan.amount}
                    </span>
                        <span className={`text-base font-medium ${
                          isRecommended ? 'text-muted-foreground' : 'text-muted-foreground'
                        }`}>
                      /{i18n?.duration || plan.duration.description}
                    </span>
                      </div>
                      
                      {isLifetime && (
                        <div className="mt-2 inline-flex items-center space-x-1 px-2.5 py-1 bg-chart-5-bg-15 text-chart-5 rounded-full text-xs font-medium">
                          <Heart className="h-3.5 w-3.5" />
                          <span>一次购买，终身使用</span>
                        </div>
                      )}
                    </div>

                    {/* Features */}
                    <div className="space-y-3 mb-6">
                      {plan.features.map((feature, featureIndex) => (
                        <div key={feature} className="flex items-start space-x-3">
                          <div className={`w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5 ${
                            isRecommended 
                              ? 'bg-chart-1' 
                              : 'bg-chart-2-bg-15'
                          }`}>
                            <Check className={`h-3 w-3 ${
                              isRecommended 
                                ? 'text-white' 
                                : 'text-chart-2'
                            }`} />
                          </div>
                          <span className={`text-sm leading-6 ${
                            isRecommended ? 'text-card-foreground' : 'text-card-foreground'
                          }`}>
                            {i18n?.features && Array.isArray(i18n.features) && featureIndex < i18n.features.length
                              ? i18n.features[featureIndex]
                          : feature}
                          </span>
                        </div>
                    ))}
                </div>

                    {/* CTA Button */}
                    <Button
                      onClick={() => handleSubscribe(plan)}
                  disabled={loading === plan.id || isPending}
                      className={`w-full py-3 rounded-lg font-semibold text-base transition-all duration-300 hover:scale-[1.02] ${
                        isRecommended
                          ? 'bg-gradient-chart-warm text-primary-foreground shadow-md hover:shadow-lg hover:opacity-90'
                          : isLifetime
                          ? 'bg-gradient-chart-cool text-primary-foreground shadow-md hover:shadow-lg hover:opacity-90'
                          : 'bg-primary text-primary-foreground shadow-md hover:shadow-lg hover:bg-primary/90'
                      } disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100`}
                >
                      {loading === plan.id ? (
                        <div className="flex items-center justify-center space-x-2">
                          <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                          <span>{t.common.loading}</span>
                        </div>
                      ) : (
                        <div className="flex items-center justify-center space-x-2">
                          <span>{t.pricing.cta}</span>
                          <ArrowRight className="h-4 w-4" />
              </div>
                      )}
                    </Button>

                    {/* Special Effects for Recommended Plan */}
                    {isRecommended && (
                      <div className="absolute inset-0 bg-gradient-chart-warm opacity-5 rounded-xl pointer-events-none"></div>
                    )}
                  </motion.div>
            );
          })}
        </div>

            {/* Additional Info */}
            <motion.div 
              className="mt-16 text-center"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.5 }}
              viewport={{ once: true }}
            >
              <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-4xl mx-auto">
                <div className="flex flex-col items-center space-y-3">
                  <div className="w-12 h-12 bg-chart-2-bg-15 rounded-xl flex items-center justify-center">
                    <Shield className="h-6 w-6 text-chart-2" />
                  </div>
                  <h4 className="font-semibold text-foreground">安全支付</h4>
                  <p className="text-sm text-muted-foreground text-center">支持微信支付、Stripe 等多种安全支付方式</p>
                </div>
                
                <div className="flex flex-col items-center space-y-3">
                  <div className="w-12 h-12 bg-chart-1-bg-15 rounded-xl flex items-center justify-center">
                    <Star className="h-6 w-6 text-chart-1" />
                  </div>
                  <h4 className="font-semibold text-foreground">终身更新</h4>
                  <p className="text-sm text-muted-foreground text-center">一次购买即可享受所有后续功能更新</p>
                </div>
                
                <div className="flex flex-col items-center space-y-3">
                  <div className="w-12 h-12 bg-chart-3-bg-15 rounded-xl flex items-center justify-center">
                    <Heart className="h-6 w-6 text-chart-3" />
                  </div>
                  <h4 className="font-semibold text-foreground">社区支持</h4>
                  <p className="text-sm text-muted-foreground text-center">加入活跃的开发者社区，获得技术支持</p>
                </div>
              </div>
            </motion.div>
          </div>
        </section>
      </div>

      {/* Payment Modal */}
      <Dialog open={!!qrCodeUrl} onOpenChange={(open) => !open && closeQrCodeModal()}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="text-center">
              {currentPlan && (
                <span>
                  {currentPlan.currency === 'CNY' ? '¥' : '$'}{currentPlan.amount} - 
                  {currentPlan.i18n && 
                   currentPlan.i18n[currentLocale] && 
                   currentPlan.i18n[currentLocale].name || currentPlan.name}
                </span>
              )}
            </DialogTitle>
          </DialogHeader>
          <div className="flex flex-col items-center space-y-6">
            <Steps steps={steps} currentStep={currentStep} />
            {qrCodeUrl && (
              <div className="flex flex-col items-center space-y-4">
                <img 
                  src={qrCodeUrl} 
                  alt="WeChat Pay QR Code" 
                  className="w-64 h-64"
                />
                <p className="text-sm text-gray-500">
                  {t.payment.scanQrCode}
                </p>
              </div>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}

// apps/nuxt-app/pages/pricing.vue
<template>
  <div>
    <!-- SEO Head -->
    <Head>
      <title>{{ t('pricing.metadata.title') }}</title>
      <meta name="description" :content="t('pricing.metadata.description')" />
      <meta name="keywords" :content="t('pricing.metadata.keywords')" />
    </Head>
    
    <div class="min-h-screen bg-background">
      <!-- Hero Section -->
      <section class="relative py-24 sm:py-32 overflow-hidden">
        <div class="mx-auto max-w-7xl px-6 lg:px-8 relative z-10">
          <motion.div 
            class="mx-auto max-w-4xl text-center"
            :initial="{ opacity: 0, y: 20 }"
            :animate="{ opacity: 1, y: 0 }"
            :transition="{ duration: 0.8 }"
          >
            <motion.div
              class="inline-flex items-center space-x-2 px-4 py-2 bg-chart-1-bg-15 rounded-full border border-chart-1/20 mb-8"
              :initial="{ opacity: 0, scale: 0.9 }"
              :animate="{ opacity: 1, scale: 1 }"
              :transition="{ duration: 0.6, delay: 0.2 }"
            >
              <Sparkles class="h-4 w-4 text-chart-1" />
              <span class="text-xs font-medium text-chart-1">{{ t('pricing.title') }}</span>
            </motion.div>

            <h2 class="text-4xl md:text-6xl font-bold tracking-tight text-foreground mb-6">
              <span class="text-gradient-chart-warm">
                {{ t('pricing.subtitle') }}
              </span>
            </h2>
            
            <p class="text-xl text-muted-foreground max-w-3xl mx-auto leading-relaxed">
              选择最适合你的方案，开始你的 TinyShip 之旅。
              一次购买，终身使用，早鸟价仅限前 100 名用户。
            </p>
          </motion.div>
        </div>
      </section>

      <!-- Pricing Cards -->
      <section class="py-24">
        <div class="mx-auto max-w-7xl px-6 lg:px-8">
          <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 lg:gap-12">
            <motion.div
              v-for="(plan, index) in plans"
              :key="plan.id"
              :class="[
                'relative rounded-xl p-6 shadow-lg transition-all duration-300 hover:scale-[1.02]',
                isRecommended(plan) 
                  ? 'bg-card border-2 border-chart-1 shadow-chart-1/20' 
                  : 'bg-card border border-border hover:border-border/80'
              ]"
              :initial="{ opacity: 0, y: 20 }"
              :whileInView="{ opacity: 1, y: 0 }"
              :transition="{ duration: 0.6, delay: index * 0.1 }"
              :viewport="{ once: true }"
            >
              <!-- Recommended Badge -->
              <div v-if="isRecommended(plan)" class="absolute -top-4 left-1/2 transform -translate-x-1/2">
                <div class="inline-flex items-center space-x-2 px-3 py-1.5 bg-gradient-chart-warm text-white rounded-full shadow-md">
                  <Crown class="h-3.5 w-3.5" />
                  <span class="text-xs font-medium">推荐选择</span>
                </div>
              </div>

              <!-- Plan Header -->
              <div class="text-center mb-6">
                <h3 :class="[
                  'text-xl font-bold mb-2',
                  isRecommended(plan) ? 'text-card-foreground' : 'text-foreground'
                ]">
                  {{ getPlanName(plan) }}
                </h3>
                
                <p :class="[
                  'text-sm',
                  isRecommended(plan) ? 'text-muted-foreground' : 'text-muted-foreground'
                ]">
                  {{ getPlanDescription(plan) }}
                </p>
              </div>

              <!-- Price -->
              <div class="text-center mb-6">
                <div class="flex items-baseline justify-center space-x-2">
                  <span :class="[
                    'text-4xl font-bold',
                    isRecommended(plan) ? 'text-card-foreground' : 'text-foreground'
                  ]">
                    {{ plan.currency === 'CNY' ? '¥' : '$' }}{{ plan.amount }}
                  </span>
                  <span :class="[
                    'text-base font-medium',
                    isRecommended(plan) ? 'text-muted-foreground' : 'text-muted-foreground'
                  ]">
                    /{{ getPlanDuration(plan) }}
                  </span>
                </div>
                
                <div v-if="isLifetime(plan)" class="mt-2 inline-flex items-center space-x-1 px-2.5 py-1 bg-chart-5-bg-15 text-chart-5 rounded-full text-xs font-medium">
                  <Heart class="h-3.5 w-3.5" />
                  <span>一次购买，终身使用</span>
                </div>
              </div>

              <!-- Features -->
              <div class="space-y-3 mb-6">
                <div
                  v-for="(feature, featureIndex) in plan.features"
                  :key="feature"
                  class="flex items-start space-x-3"
                >
                  <div :class="[
                    'w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5',
                    isRecommended(plan) 
                      ? 'bg-chart-1' 
                      : 'bg-chart-2-bg-15'
                  ]">
                    <Check :class="[
                      'h-3 w-3',
                      isRecommended(plan) 
                        ? 'text-white' 
                        : 'text-chart-2'
                    ]" />
                  </div>
                  <span :class="[
                    'text-sm leading-6',
                    isRecommended(plan) ? 'text-card-foreground' : 'text-card-foreground'
                  ]">
                    {{ getPlanFeature(plan, featureIndex) }}
                  </span>
                </div>
              </div>

              <!-- CTA Button -->
              <Button
                @click="handleSubscribe(plan)"
                :disabled="loading === plan.id || session.isPending"
                :class="[
                  'w-full py-3 rounded-lg font-semibold text-base transition-all duration-300 hover:scale-[1.02]',
                  isRecommended(plan)
                    ? 'bg-gradient-chart-warm text-primary-foreground shadow-md hover:shadow-lg hover:opacity-90'
                    : isLifetime(plan)
                    ? 'bg-gradient-chart-cool text-primary-foreground shadow-md hover:shadow-lg hover:opacity-90'
                    : 'bg-primary text-primary-foreground shadow-md hover:shadow-lg hover:bg-primary/90',
                  'disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100'
                ]"
              >
                <div v-if="loading === plan.id" class="flex items-center justify-center space-x-2">
                  <div class="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                  <span>{{ t('common.loading') }}</span>
                </div>
                <div v-else class="flex items-center justify-center space-x-2">
                  <span>{{ t('pricing.cta') }}</span>
                  <ArrowRight class="h-4 w-4" />
                </div>
              </Button>

              <!-- Special Effects for Recommended Plan -->
              <div v-if="isRecommended(plan)" class="absolute inset-0 bg-gradient-chart-warm opacity-5 rounded-xl pointer-events-none"></div>
            </motion.div>
          </div>

          <!-- Additional Info -->
          <motion.div 
            class="mt-16 text-center"
            :initial="{ opacity: 0, y: 20 }"
            :whileInView="{ opacity: 1, y: 0 }"
            :transition="{ duration: 0.6, delay: 0.5 }"
            :viewport="{ once: true }"
          >
            <div class="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-4xl mx-auto">
              <div class="flex flex-col items-center space-y-3">
                <div class="w-12 h-12 bg-chart-2-bg-15 rounded-xl flex items-center justify-center">
                  <Shield class="h-6 w-6 text-chart-2" />
                </div>
                <h4 class="font-semibold text-foreground">安全支付</h4>
                <p class="text-sm text-muted-foreground text-center">支持微信支付、Stripe 等多种安全支付方式</p>
              </div>
              
              <div class="flex flex-col items-center space-y-3">
                <div class="w-12 h-12 bg-chart-1-bg-15 rounded-xl flex items-center justify-center">
                  <Star class="h-6 w-6 text-chart-1" />
                </div>
                <h4 class="font-semibold text-foreground">终身更新</h4>
                <p class="text-sm text-muted-foreground text-center">一次购买即可享受所有后续功能更新</p>
              </div>
              
              <div class="flex flex-col items-center space-y-3">
                <div class="w-12 h-12 bg-chart-3-bg-15 rounded-xl flex items-center justify-center">
                  <Heart class="h-6 w-6 text-chart-3" />
                </div>
                <h4 class="font-semibold text-foreground">社区支持</h4>
                <p class="text-sm text-muted-foreground text-center">加入活跃的开发者社区，获得技术支持</p>
              </div>
            </div>
          </motion.div>
        </div>
      </section>
    </div>

    <!-- Payment Modal -->
    <Dialog :open="!!qrCodeUrl" @update:open="(open) => !open && closeQrCodeModal()">
      <DialogContent class="sm:max-w-md">
        <DialogHeader>
          <DialogTitle class="text-center">
            <span v-if="currentPlan">
              {{ currentPlan.currency === 'CNY' ? '¥' : '$' }}{{ currentPlan.amount }} - 
              {{ getPlanName(currentPlan) }}
            </span>
          </DialogTitle>
        </DialogHeader>
        <div class="flex flex-col items-center space-y-6">
          <!-- Payment Steps -->
          <div class="w-full max-w-sm">
            <div class="flex items-center justify-between mb-4">
              <div
                v-for="(step, index) in steps"
                :key="index"
                class="flex items-center"
              >
                <div :class="[
                  'flex items-center justify-center w-8 h-8 rounded-full text-sm font-medium',
                  index <= currentStep ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'
                ]">
                  {{ index + 1 }}
                </div>
                <div v-if="index < steps.length - 1" :class="[
                  'flex-1 h-0.5 mx-2',
                  index < currentStep ? 'bg-primary' : 'bg-muted'
                ]"></div>
              </div>
            </div>
            <div class="text-center">
              <h4 class="font-medium">{{ steps[currentStep]?.title }}</h4>
              <p class="text-sm text-muted-foreground">{{ steps[currentStep]?.description }}</p>
            </div>
          </div>

          <!-- QR Code -->
          <div v-if="qrCodeUrl" class="flex flex-col items-center space-y-4">
            <img 
              :src="qrCodeUrl" 
              alt="WeChat Pay QR Code" 
              class="w-64 h-64"
            />
            <p class="text-sm text-muted-foreground text-center">
              {{ t('payment.scanQrCode') }}
            </p>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onUnmounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { toast } from 'vue-sonner'
import { Check, Star, Crown, Heart, ArrowRight, Shield, Sparkles } from 'lucide-vue-next'
import { motion } from 'motion-v'
import type { Plan } from '@config'

// Get config data
const runtimeConfig = useRuntimeConfig()
const plans = computed(() => Object.values(runtimeConfig.public.paymentPlans) as Plan[])

// Authentication - Use Better Auth composable
const { user, isAuthenticated, session } = useAuth()

// Router and i18n
const router = useRouter()
const route = useRoute()
const { locale, t } = useI18n()
const localePath = useLocalePath()

// Reactive state
const loading = ref<string | null>(null)
const qrCodeUrl = ref<string | null>(null)
const currentPlan = ref<Plan | null>(null)
const currentStep = ref(0)
const orderId = ref<string | null>(null)
const pollingInterval = ref<NodeJS.Timeout | null>(null)

// Payment steps
const steps = computed(() => [
  { title: t('payment.steps.initiate'), description: t('payment.steps.initiateDesc') },
  { title: t('payment.steps.scan'), description: t('payment.steps.scanDesc') },
  { title: t('payment.steps.pay'), description: t('payment.steps.payDesc') },
])

// Helper functions
const isRecommended = (plan: Plan) => plan.recommended
const isLifetime = (plan: Plan) => plan.id === 'lifetime'

const getPlanName = (plan: Plan) => {
  const i18n = plan.i18n?.[locale.value]
  return i18n?.name || plan.name
}

const getPlanDescription = (plan: Plan) => {
  const i18n = plan.i18n?.[locale.value]
  return i18n?.description || plan.description
}

const getPlanDuration = (plan: Plan) => {
  const i18n = plan.i18n?.[locale.value]
  return i18n?.duration || plan.duration.description
}

const getPlanFeature = (plan: Plan, index: number) => {
  const i18n = plan.i18n?.[locale.value]
  if (i18n?.features && Array.isArray(i18n.features) && index < i18n.features.length) {
    return i18n.features[index]
  }
  return plan.features[index]
}

// Payment polling
const startPolling = (orderIdValue: string) => {
  // Clear existing polling
  if (pollingInterval.value) {
    clearInterval(pollingInterval.value)
  }

  const interval = setInterval(async () => {
    try {
      const response = await $fetch(`/api/payment/query?orderId=${orderIdValue}&provider=wechat`) as any

      if (response.status === 'paid') {
        clearInterval(interval)
        pollingInterval.value = null
        await navigateTo(localePath(`/payment-success?provider=wechat`))
      } else if (response.status === 'failed') {
        clearInterval(interval)
        pollingInterval.value = null
        toast.error(t('payment.result.failed'))
        closeQrCodeModal()
      }
    } catch (error) {
      console.error('Payment polling error:', error)
    }
  }, 3000) // Poll every 3 seconds

  pollingInterval.value = interval
}

// Handle subscription
const handleSubscribe = async (plan: Plan) => {
  try {
    if (!user.value) {
      const returnPath = encodeURIComponent(route.fullPath)
      await navigateTo(localePath(`/signin?returnTo=${returnPath}`))
      return
    }

    loading.value = plan.id
    const provider = plan.provider || 'stripe'
    currentPlan.value = plan
    
    const response = await $fetch('/api/payment/initiate', {
      method: 'POST',
      body: {
        planId: plan.id,
        provider
      }
    })
    
    if (provider === 'wechat') {
      if (response.paymentUrl) {
        try {
          // Generate QR code (we'll need to install qrcode package)
          const QRCode = await import('qrcode')
          const qrDataUrl = await QRCode.toDataURL(response.paymentUrl)
          qrCodeUrl.value = qrDataUrl
          orderId.value = response.providerOrderId
          currentStep.value = 1
          startPolling(response.providerOrderId)
        } catch (err) {
          console.error('QR code generation error:', err)
          toast.error(t('common.unexpectedError'))
        }
      }
    } else {
      if (response.paymentUrl) {
        window.location.href = response.paymentUrl
      }
    }
  } catch (error) {
    console.error('Payment error:', error)
    toast.error(t('common.unexpectedError'))
  } finally {
    loading.value = null
  }
}

// Close QR code modal
const closeQrCodeModal = async () => {
  // If payment is in progress, confirm cancellation
  if (currentStep.value < 2 && orderId.value) {
    const confirmCancel = window.confirm(t('payment.confirmCancel'))
    if (!confirmCancel) {
      return // User cancelled the close, continue payment flow
    }
    
    // Call cancel order API
    try {
      await $fetch(`/api/payment/cancel?orderId=${orderId.value}&provider=wechat`, {
        method: 'POST'
      })
      toast.info(t('payment.orderCanceled'))
    } catch (error) {
      console.error('Cancel order error:', error)
      toast.error(t('common.unexpectedError'))
    }
  }
  
  qrCodeUrl.value = null
  currentPlan.value = null
  currentStep.value = 0
  orderId.value = null
  if (pollingInterval.value) {
    clearInterval(pollingInterval.value)
    pollingInterval.value = null
  }
}

// Cleanup on unmount
onUnmounted(() => {
  if (pollingInterval.value) {
    clearInterval(pollingInterval.value)
  }
})

// SEO
useHead({
  title: () => t('pricing.metadata.title'),
  meta: [
    { name: 'description', content: () => t('pricing.metadata.description') },
    { name: 'keywords', content: () => t('pricing.metadata.keywords') }
  ]
})
</script>
