// apps/nuxt-app/components/ChangePasswordDialog.vue
<script setup lang="ts">
import { authClientVue } from "@libs/auth/authClient"
import { toast } from 'vue-sonner'
import { toTypedSchema } from '@vee-validate/zod'
import { useForm } from 'vee-validate'
import { createValidators } from '@libs/validators'
import { cn } from '@/lib/utils'

const { t } = useI18n()

interface Props {
  open: boolean
}

interface Emits {
  (e: 'update:open', open: boolean): void
}

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

const loading = ref(false)

// Create internationalized validators
const { changePasswordSchema } = createValidators(t)

// Form validation using vee-validate
const { handleSubmit, errors, defineField, isSubmitting, resetForm } = useForm({
  validationSchema: toTypedSchema(changePasswordSchema),
  initialValues: {
    currentPassword: '',
    newPassword: '',
    confirmPassword: ''
  }
})

// Define form fields with validation
const [currentPassword, currentPasswordAttrs] = defineField('currentPassword', {
  validateOnBlur: true
})
const [newPassword, newPasswordAttrs] = defineField('newPassword', {
  validateOnBlur: true
})
const [confirmPassword, confirmPasswordAttrs] = defineField('confirmPassword', {
  validateOnBlur: true
})

/**
 * Submit form to change password
 */
const onSubmit = handleSubmit(async (values) => {
  loading.value = true
  try {
    await authClientVue.changePassword({
      newPassword: values.newPassword,
      currentPassword: values.currentPassword,
      revokeOtherSessions: true
    })
    
    // Show success message
    toast.success(t('dashboard.accountManagement.changePassword.success'))
    
    // Reset form and close dialog
    resetForm()
    emit('update:open', false)
    
  } catch (error) {
    console.error('Failed to change password:', error)
    toast.error(t('dashboard.accountManagement.changePassword.errors.failed'))
  } finally {
    loading.value = false
  }
})

/**
 * Cancel operation and reset form
 */
const handleCancel = () => {
  resetForm()
  emit('update:open', false)
}
</script>

<template>
  <Dialog :open="open" @update:open="emit('update:open', $event)">
    <DialogContent class="sm:max-w-[425px]">
      <DialogHeader>
        <DialogTitle>{{ t('dashboard.accountManagement.changePassword.title') }}</DialogTitle>
        <DialogDescription>
          {{ t('dashboard.accountManagement.changePassword.dialogDescription') }}
        </DialogDescription>
      </DialogHeader>
      
      <form @submit.prevent="onSubmit" class="space-y-4">
        <!-- Current password -->
        <div class="grid gap-2">
          <Label for="current-password">
            {{ t('dashboard.accountManagement.changePassword.form.currentPassword') }}
          </Label>
          <div class="relative">
            <Input
              id="current-password"
              v-bind="currentPasswordAttrs"
              v-model="currentPassword"
              type="password"
              :placeholder="t('dashboard.accountManagement.changePassword.form.currentPasswordPlaceholder')"
              :class="cn(errors.currentPassword && 'border-destructive')"
              :aria-invalid="errors.currentPassword ? 'true' : 'false'"
              autocomplete="current-password"
            />
            <span v-if="errors.currentPassword" class="text-destructive text-xs absolute -bottom-5 left-0">
              {{ errors.currentPassword }}
            </span>
          </div>
        </div>
        
        <!-- New password -->
        <div class="grid gap-2">
          <Label for="new-password">
            {{ t('dashboard.accountManagement.changePassword.form.newPassword') }}
          </Label>
          <div class="relative">
            <Input
              id="new-password"
              v-bind="newPasswordAttrs"
              v-model="newPassword"
              type="password"
              :placeholder="t('dashboard.accountManagement.changePassword.form.newPasswordPlaceholder')"
              :class="cn(errors.newPassword && 'border-destructive')"
              :aria-invalid="errors.newPassword ? 'true' : 'false'"
              autocomplete="new-password"
            />
            <span v-if="errors.newPassword" class="text-destructive text-xs absolute -bottom-5 left-0">
              {{ errors.newPassword }}
            </span>
          </div>
        </div>
        
        <!-- Confirm new password -->
        <div class="grid gap-2">
          <Label for="confirm-password">
            {{ t('dashboard.accountManagement.changePassword.form.confirmPassword') }}
          </Label>
          <div class="relative">
            <Input
              id="confirm-password"
              v-bind="confirmPasswordAttrs"
              v-model="confirmPassword"
              type="password"
              :placeholder="t('dashboard.accountManagement.changePassword.form.confirmPasswordPlaceholder')"
              :class="cn(errors.confirmPassword && 'border-destructive')"
              :aria-invalid="errors.confirmPassword ? 'true' : 'false'"
              autocomplete="new-password"
            />
            <span v-if="errors.confirmPassword" class="text-destructive text-xs absolute -bottom-5 left-0">
              {{ errors.confirmPassword }}
            </span>
          </div>
        </div>
        
        <DialogFooter>
          <Button type="button" variant="outline" @click="handleCancel">
            {{ t('dashboard.accountManagement.changePassword.form.cancel') }}
          </Button>
          <Button 
            type="submit" 
            :disabled="loading || isSubmitting"
          >
            {{ loading || isSubmitting ? t('common.loading') : t('dashboard.accountManagement.changePassword.form.submit') }}
          </Button>
        </DialogFooter>
      </form>
    </DialogContent>
  </Dialog>
</template>

// apps/next-app/app/[lang]/(root)/dashboard/components/change-password-dialog.tsx
'use client';

import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { authClientReact } from "@libs/auth/authClient";
import { createValidators } from "@libs/validators";
import type { z } from "zod";
import { toast } from "sonner";
import { useTranslation } from "@/hooks/use-translation";
import { cn } from "@/lib/utils";

interface ChangePasswordDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function ChangePasswordDialog({ open, onOpenChange }: ChangePasswordDialogProps) {
  const { t, tWithParams } = useTranslation();
  const [loading, setLoading] = useState(false);

  // 创建国际化验证器
  const { changePasswordSchema } = createValidators(tWithParams);
  
  type FormData = z.infer<typeof changePasswordSchema>;

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
    reset
  } = useForm<FormData>({
    resolver: zodResolver(changePasswordSchema),
    defaultValues: {
      currentPassword: '',
      newPassword: '',
      confirmPassword: ''
    },
    mode: 'onBlur',
  });

  // 处理密码更改
  const onSubmit = async (formData: FormData) => {
    setLoading(true);
    try {
      await authClientReact.changePassword({
        newPassword: formData.newPassword,
        currentPassword: formData.currentPassword,
        revokeOtherSessions: true,
      });

      toast.success(t.dashboard.accountManagement.changePassword.success);
      handleClose();
    } catch (error) {
      console.error('Failed to change password:', error);
      toast.error(t.dashboard.accountManagement.changePassword.errors.failed);
    } finally {
      setLoading(false);
    }
  };

  const handleClose = () => {
    onOpenChange(false);
    reset();
  };

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{t.dashboard.accountManagement.changePassword.title}</DialogTitle>
          <DialogDescription>
            {t.dashboard.accountManagement.changePassword.dialogDescription}
          </DialogDescription>
        </DialogHeader>
        
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="currentPassword">
              {t.dashboard.accountManagement.changePassword.form.currentPassword}
            </Label>
            <div className="relative">
              <Input
                id="currentPassword"
                type="password"
                autoComplete="current-password"
                {...register('currentPassword')}
                placeholder={t.dashboard.accountManagement.changePassword.form.currentPasswordPlaceholder}
                className={cn(errors.currentPassword && "border-destructive")}
                aria-invalid={errors.currentPassword ? "true" : "false"}
              />
              {errors.currentPassword && (
                <span className="text-destructive text-xs mt-1 block">
                  {errors.currentPassword.message}
                </span>
              )}
            </div>
          </div>
          
          <div className="space-y-2">
            <Label htmlFor="newPassword">
              {t.dashboard.accountManagement.changePassword.form.newPassword}
            </Label>
            <div className="relative">
              <Input
                id="newPassword"
                type="password"
                autoComplete="new-password"
                {...register('newPassword')}
                placeholder={t.dashboard.accountManagement.changePassword.form.newPasswordPlaceholder}
                className={cn(errors.newPassword && "border-destructive")}
                aria-invalid={errors.newPassword ? "true" : "false"}
              />
              {errors.newPassword && (
                <span className="text-destructive text-xs mt-1 block">
                  {errors.newPassword.message}
                </span>
              )}
            </div>
          </div>
          
          <div className="space-y-2">
            <Label htmlFor="confirmPassword">
              {t.dashboard.accountManagement.changePassword.form.confirmPassword}
            </Label>
            <div className="relative">
              <Input
                id="confirmPassword"
                type="password"
                autoComplete="new-password"
                {...register('confirmPassword')}
                placeholder={t.dashboard.accountManagement.changePassword.form.confirmPasswordPlaceholder}
                className={cn(errors.confirmPassword && "border-destructive")}
                aria-invalid={errors.confirmPassword ? "true" : "false"}
              />
              {errors.confirmPassword && (
                <span className="text-destructive text-xs mt-1 block">
                  {errors.confirmPassword.message}
                </span>
              )}
            </div>
          </div>

          <DialogFooter>
            <Button 
              type="button"
              variant="outline" 
              onClick={handleClose}
              disabled={loading || isSubmitting}
            >
              {t.dashboard.accountManagement.changePassword.form.cancel}
            </Button>
            <Button 
              type="submit"
              disabled={loading || isSubmitting}
            >
              {loading || isSubmitting ? (
                <div className="animate-spin h-4 w-4 border-2 border-primary border-t-transparent rounded-full mr-2" />
              ) : null}
              {t.dashboard.accountManagement.changePassword.form.submit}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
