// apps/nuxt-app/components/LinkedAccountsCard.vue
<script setup lang="ts">
import { authClientVue } from "@libs/auth/authClient"

const { t } = useI18n()

interface LinkedAccount {
  id: string
  providerId?: string
  provider?: string // Next.js 版本使用 provider 字段
  accountId: string
  createdAt: string | Date
}

const linkedAccounts = ref<LinkedAccount[]>([])
const loading = ref(true)

/**
 * Fetch linked accounts data from Better Auth
 */
const fetchLinkedAccounts = async () => {
  const { data, error } = await authClientVue.listAccounts()
  
  if (error) {
    console.error('Failed to fetch linked accounts:', error)
    linkedAccounts.value = []
    loading.value = false
    return
  }
  
  // 根据实际返回的数据结构设置账户列表
  if (data) {
    linkedAccounts.value = data
  } else {
    linkedAccounts.value = []
  }
  
  loading.value = false
}

/**
 * Format date according to locale
 * @param dateString - Date string or Date object
 * @returns Formatted date string
 */
const formatDate = (dateString: string | Date) => {
  const date = typeof dateString === 'string' ? new Date(dateString) : dateString
  return date.toLocaleDateString('zh-CN', {
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  })
}

/**
 * Get provider display name from i18n
 * @param account - Account object
 * @returns Localized provider name
 */
const getProviderDisplayName = (account: LinkedAccount) => {
  let provider = account.provider || account.providerId || 'unknown'
  
  // 处理单复数差异：credential -> credentials
  if (provider === 'credential') {
    provider = 'credentials'
  }
  
  const providerKey = `dashboard.linkedAccounts.providers.${provider}` as const
  return t(providerKey)
}

// Fetch data when component is mounted
onMounted(() => {
  fetchLinkedAccounts()
})
</script>

<template>
  <div>
    <h3 class="text-lg font-medium mb-4">{{ t('dashboard.linkedAccounts.title') }}</h3>
    
    <!-- Loading state -->
    <div v-if="loading" class="animate-pulse">
      <div class="h-4 bg-muted rounded w-32 mb-2"></div>
      <div class="h-4 bg-muted rounded w-48"></div>
    </div>
    
    <!-- Linked accounts list -->
    <div v-if="!loading && linkedAccounts.length > 0" class="space-y-3">
      <div 
        v-for="account in linkedAccounts" 
        :key="account.id"
        class="flex items-center justify-between p-4 border rounded-lg"
      >
        <div class="flex items-center space-x-3">
          <div class="w-8 h-8 rounded-full bg-muted flex items-center justify-center">
            <!-- Icon can be added here -->
            <div class="w-4 h-4 bg-primary rounded-full"></div>
          </div>
          <div>
            <p class="font-medium">{{ getProviderDisplayName(account) }}</p>
            <p class="text-sm text-muted-foreground">
              {{ t('dashboard.linkedAccounts.connectedAt') }} {{ formatDate(account.createdAt) }}
            </p>
          </div>
        </div>
        <Badge variant="secondary">
          {{ t('dashboard.linkedAccounts.connected') }}
        </Badge>
      </div>
    </div>
    
    <!-- No linked accounts -->
    <div v-else-if="!loading && linkedAccounts.length === 0" class="text-center p-8 text-muted-foreground">
      <p>{{ t('dashboard.linkedAccounts.noLinkedAccounts') }}</p>
    </div>
  </div>
</template>

// apps/next-app/app/[lang]/(root)/dashboard/components/linked-accounts-card.tsx
'use client';

import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { 
  Link as LinkIcon,
  Mail,
  Key
} from "lucide-react";
import { authClientReact } from "@libs/auth/authClient";
import { useTranslation } from "@/hooks/use-translation";

interface LinkedAccountsCardProps {
  // Props interface if needed
}

export function LinkedAccountsCard({}: LinkedAccountsCardProps) {
  const { t, locale: currentLocale } = useTranslation();
  const [accountsData, setAccountsData] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchAccountsData() {
      const { data, error } = await authClientReact.listAccounts();
      
      if (error) {
        console.error('Failed to fetch user accounts', error);
        setAccountsData([]);
        setLoading(false);
        return;
      }
      
      if (data) {
        setAccountsData(data);
      } else {
        setAccountsData([]);
      }
      
      setLoading(false);
    }

    fetchAccountsData();
  }, []);

  // 格式化日期
  const formatDate = (dateString: string | Date) => {
    const date = typeof dateString === 'string' ? new Date(dateString) : dateString;
    return date.toLocaleDateString(currentLocale === 'zh-CN' ? 'zh-CN' : 'en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  };

  // 获取提供商显示名称
  const getProviderDisplayName = (provider: string) => {
    const providerKey = provider.toLowerCase() as keyof typeof t.dashboard.linkedAccounts.providers;
    return t.dashboard.linkedAccounts.providers[providerKey] || provider;
  };

  // 获取提供商图标
  const getProviderIcon = (provider: string) => {
    switch (provider.toLowerCase()) {
      case 'credentials':
        return Mail;
      case 'phone':
        return Key;
      default:
        return LinkIcon;
    }
  };

  if (loading) {
    return (
      <div>
        <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
          <LinkIcon className="h-5 w-5" />
          {t.dashboard.linkedAccounts.title}
        </h3>
        <div className="animate-pulse space-y-3">
          {[1, 2].map((i) => (
            <div key={i} className="flex items-center justify-between p-3 rounded-lg border bg-muted/20">
              <div className="flex items-center gap-3">
                <div className="h-8 w-8 bg-muted rounded-full"></div>
                <div>
                  <div className="h-4 bg-muted rounded w-20 mb-1"></div>
                  <div className="h-3 bg-muted rounded w-32"></div>
                </div>
              </div>
              <div className="h-6 bg-muted rounded w-16"></div>
            </div>
          ))}
        </div>
      </div>
    );
  }

  return (
    <div>
      <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
        <LinkIcon className="h-5 w-5" />
        {t.dashboard.linkedAccounts.title}
      </h3>
      <div className="space-y-3">
        {accountsData.length > 0 ? (
          accountsData.map((account) => {
            const ProviderIcon = getProviderIcon(account.provider);
            return (
              <div
                key={account.id}
                className="flex items-center justify-between p-3 rounded-lg border bg-muted/20"
              >
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-full bg-background border">
                    <ProviderIcon className="h-4 w-4" />
                  </div>
                  <div>
                    <div className="font-medium">
                      {getProviderDisplayName(account.provider)}
                    </div>
                    <div className="text-sm text-muted-foreground">
                      {t.dashboard.linkedAccounts.connectedAt} {formatDate(account.createdAt)}
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <Badge variant="secondary" className="text-xs">
                    {t.dashboard.linkedAccounts.connected}
                  </Badge>
                </div>
              </div>
            );
          })
        ) : (
          <div className="text-center py-6 text-muted-foreground">
            <LinkIcon className="h-12 w-12 mx-auto mb-2 opacity-50" />
            <p>
              {t.dashboard.linkedAccounts.noLinkedAccounts}
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
