// apps/next-app/components/ui/form-error.tsx
import { Alert, AlertDescription } from "@/components/ui/alert"
import { ExclamationTriangleIcon } from "@radix-ui/react-icons"

interface FormErrorProps {
  message?: string;
  code?: string;
}

export function FormError({ message, code }: FormErrorProps) {
  if (!message) return null;

  return (
    <Alert variant="destructive" className="mb-6">
      <ExclamationTriangleIcon className="h-4 w-4" />
      <AlertDescription>{message} - {code}</AlertDescription>
    </Alert>
  );
}

// apps/nuxt-app/components/FormError.vue
<template>
  <Alert v-if="message" variant="destructive" class="mb-6">
    <ExclamationTriangleIcon class="h-4 w-4" />
    <AlertDescription>{{ message }} {{ code ? `- ${code}` : '' }}</AlertDescription>
  </Alert>
</template>

<script setup lang="ts">
// 导入图标组件 (使用 lucide-vue-next)
import { AlertTriangle as ExclamationTriangleIcon } from 'lucide-vue-next'

interface Props {
  message?: string
  code?: string
}

defineProps<Props>()
</script>
