// apps/next-app/src/components/global-header.tsx
"use client";

import Link from "next/link";
import { useState } from "react";
import { Button } from "./ui/button";
import { authClientReact } from "@libs/auth/authClient";
import Image from "next/image";
import { useRouter } from "next/navigation";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "./ui/dropdown-menu";
import { Avatar, AvatarFallback, AvatarImage } from "./ui/avatar";

interface HeaderProps {
  className?: string;
}

export default function Header({ className }: HeaderProps) {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const router = useRouter();
  
  const { 
    data: session, 
    isPending
  } = authClientReact.useSession();
  console.log('session', session)
  const user = session?.user;

  const handleSignOut = async () => {
    await authClientReact.signOut();
    router.push('/');
  };

  return (
    <header className={`w-full bg-white/90 backdrop-blur-sm border-b border-indigo-100 sticky top-0 z-40 ${className}`}>
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex h-16 items-center justify-between">
          {/* Logo and brand */}
          <div className="flex items-center">
            <Link href="/" className="flex items-center space-x-2">
              <div className="h-8 w-8 rounded-full bg-gradient-to-br from-blue-600 to-purple-600 flex items-center justify-center text-white font-bold">S</div>
              <span className="text-xl font-bold bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600 bg-clip-text text-transparent">ShipEasy</span>
            </Link>
          </div>

          {/* Desktop navigation */}
          <nav className="hidden md:flex md:space-x-8">
            <Link href="/features" className="text-sm font-medium text-gray-600 hover:text-indigo-600 transition-colors">
              Features
            </Link>
            <Link href="/pricing" className="text-sm font-medium text-gray-600 hover:text-indigo-600 transition-colors">
              Pricing
            </Link>
            <Link href="/about" className="text-sm font-medium text-gray-600 hover:text-indigo-600 transition-colors">
              About
            </Link>
          </nav>

          {/* User menu or Auth buttons */}
          <div className="hidden md:flex items-center space-x-4">
            {isPending ? (
              <div className="h-8 w-8 rounded-full bg-blue-100 animate-pulse"></div>
            ) : user ? (
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <button className="flex items-center space-x-2 focus:outline-none">
                    <Avatar className="h-8 w-8 border border-blue-100">
                      <AvatarImage src={user.image || ""} alt={user.name || user.email || "User"} />
                      <AvatarFallback className="bg-blue-50 text-blue-700 text-xs">
                        {user.name?.charAt(0) || user.email?.charAt(0) || "U"}
                      </AvatarFallback>
                    </Avatar>
                    <span className="text-sm font-medium text-gray-700">{user.name || user.email}</span>
                  </button>
                </DropdownMenuTrigger>
                <DropdownMenuContent className="w-56" align="end">
                  <DropdownMenuLabel>
                    <div className="flex flex-col space-y-1">
                      <p className="text-sm font-medium">{user.name || "User"}</p>
                      <p className="text-xs text-muted-foreground">{user.email}</p>
                    </div>
                  </DropdownMenuLabel>
                  <DropdownMenuSeparator />
                  <DropdownMenuGroup>
                    <DropdownMenuItem asChild>
                      <Link href="/dashboard" className="flex items-center">
                        <svg className="mr-2 h-4 w-4 text-blue-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                          <rect x="3" y="3" width="7" height="7"></rect>
                          <rect x="14" y="3" width="7" height="7"></rect>
                          <rect x="14" y="14" width="7" height="7"></rect>
                          <rect x="3" y="14" width="7" height="7"></rect>
                        </svg>
                        Dashboard
                      </Link>
                    </DropdownMenuItem>
                    <DropdownMenuItem asChild>
                      <Link href="/profile" className="flex items-center">
                        <svg className="mr-2 h-4 w-4 text-blue-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                          <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                          <circle cx="12" cy="7" r="4"></circle>
                        </svg>
                        Profile
                      </Link>
                    </DropdownMenuItem>
                    <DropdownMenuItem asChild>
                      <Link href="/settings" className="flex items-center">
                        <svg className="mr-2 h-4 w-4 text-blue-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                          <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"></path>
                          <circle cx="12" cy="12" r="3"></circle>
                        </svg>
                        Settings
                      </Link>
                    </DropdownMenuItem>
                  </DropdownMenuGroup>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem className="text-red-600" onClick={handleSignOut}>
                    <svg className="mr-2 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
                      <polyline points="16 17 21 12 16 7"></polyline>
                      <line x1="21" y1="12" x2="9" y2="12"></line>
                    </svg>
                    Sign out
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            ) : (
              <>
                <Link href="/signin">
                  <Button variant="ghost" className="text-sm font-medium text-gray-700 hover:text-blue-600 hover:bg-blue-50">
                    Sign in
                  </Button>
                </Link>
                <Link href="/signup">
                  <Button variant="default" className="text-sm font-medium bg-blue-600 text-white hover:bg-blue-700 border-0">
                    Sign up
                  </Button>
                </Link>
                <Link href="/cellphone">
                  <Button variant="ghost" className="text-sm font-medium text-gray-700 hover:text-blue-600 hover:bg-blue-50">
                    Sign in with phone
                  </Button>
                </Link>
              </>
            )}
          </div>

          {/* Mobile menu button */}
          <div className="flex md:hidden">
            <button
              onClick={() => setIsMenuOpen(!isMenuOpen)}
              className="inline-flex items-center justify-center p-2 rounded-md text-gray-500 hover:text-blue-600 hover:bg-blue-50 focus:outline-none transition-colors"
            >
              <span className="sr-only">Open main menu</span>
              {/* Hamburger icon */}
              {!isMenuOpen ? (
                <svg className="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
                </svg>
              ) : (
                <svg className="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              )}
            </button>
          </div>
        </div>
      </div>

      {/* Mobile menu */}
      {isMenuOpen && (
        <div className="md:hidden bg-white border-t border-blue-50">
          <div className="px-2 pt-2 pb-3 space-y-1 sm:px-3">
            <Link href="/features" className="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-blue-600 hover:bg-blue-50">
              Features
            </Link>
            <Link href="/pricing" className="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-blue-600 hover:bg-blue-50">
              Pricing
            </Link>
            <Link href="/about" className="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-blue-600 hover:bg-blue-50">
              About
            </Link>
          </div>
          <div className="pt-4 pb-3 border-t border-blue-100">
            {user ? (
              <div className="px-4 space-y-1">
                <div className="flex items-center px-3">
                  <div className="flex-shrink-0">
                    <Avatar className="h-10 w-10 border border-blue-100">
                      <AvatarImage src={user.image || ""} alt={user.name || user.email || "User"} />
                      <AvatarFallback className="bg-blue-50 text-blue-700 text-sm">
                        {user.name?.charAt(0) || user.email?.charAt(0) || "U"}
                      </AvatarFallback>
                    </Avatar>
                  </div>
                  <div className="ml-3">
                    <div className="text-base font-medium text-gray-800">{user.name || "User"}</div>
                    <div className="text-sm font-medium text-gray-500">{user.email}</div>
                  </div>
                </div>
                <Link href="/dashboard" className="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-blue-600 hover:bg-blue-50">
                  Dashboard
                </Link>
                <Link href="/profile" className="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-blue-600 hover:bg-blue-50">
                  Profile
                </Link>
                <Link href="/settings" className="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-blue-600 hover:bg-blue-50">
                  Settings
                </Link>
                <button
                  onClick={handleSignOut}
                  className="block w-full text-left px-3 py-2 rounded-md text-base font-medium text-red-600 hover:bg-red-50"
                >
                  Sign out
                </button>
              </div>
            ) : (
              <div className="flex items-center justify-center space-x-4 px-4 py-2">
                <Link href="/signin" className="w-1/2">
                  <Button variant="outline" className="w-full text-sm font-medium border-blue-200 text-blue-700 hover:bg-blue-50">
                    Sign in
                  </Button>
                </Link>
                <Link href="/signup" className="w-1/2">
                  <Button variant="default" className="w-full text-sm font-medium bg-blue-600 hover:bg-blue-700 border-0">
                    Sign up
                  </Button>
                </Link>
              </div>
            )}
          </div>
        </div>
      )}
    </header>
  );
}

// apps/nuxt-app/components/GlobalHeader.vue
<template>
  <header class="w-full bg-background/90 backdrop-blur-sm border-b border-border sticky top-0 z-40">
    <div class="container mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex h-16 items-center justify-between">
        <!-- Logo and brand -->
        <div class="flex items-center">
          <NuxtLink :to="localePath('/')">
            <AppLogo size="lg" />
          </NuxtLink>
        </div>

        <!-- Desktop navigation -->
        <nav class="hidden md:flex md:space-x-8">
          <NuxtLink 
            :to="localePath('/ai')" 
            class="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
          >
            {{ t('header.navigation.ai') }}
          </NuxtLink>
          <NuxtLink 
            :to="localePath('/premium-features')" 
            class="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
          >
            {{ t('header.navigation.premiumFeatures') }}
          </NuxtLink>
          <NuxtLink 
            :to="localePath('/pricing')" 
            class="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
          >
            {{ t('header.navigation.pricing') }}
          </NuxtLink>
        </nav>

        <!-- Right side actions -->
        <div class="hidden md:flex md:items-center md:space-x-4">
          <!-- Language switcher -->
          <DropdownMenu>
            <DropdownMenuTrigger as-child>
              <Button variant="ghost" size="sm" class="h-8 w-8 px-0">
                <span class="sr-only">{{ t('header.language.switchLanguage') }}</span>
                <svg class="h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <circle cx="12" cy="12" r="10"/>
                  <path d="M2 12h20"/>
                  <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/>
                </svg>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem 
                v-for="localeOption in availableLocales" 
                :key="localeOption.code"
                @click="changeLanguage(localeOption.code)"
                :class="{ 'bg-accent': localeOption.code === locale }"
              >
                <span class="mr-2 text-lg">{{ localeOption.flag }}</span>
                {{ localeOption.name }}
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>

          <!-- Theme toggle -->
          <ThemeToggle />

          <!-- User menu or Auth buttons -->
          <div class="flex items-center space-x-2">
            <DropdownMenu v-if="user">
              <DropdownMenuTrigger as-child>
                <button class="flex items-center space-x-2 focus:outline-none">
                  <Avatar class="h-8 w-8 border border-border">
                    <AvatarImage :src="user.image || ''" :alt="user.name || user.email || 'User'" />
                    <AvatarFallback class="bg-muted text-muted-foreground text-xs">
                      {{ (user.name?.charAt(0) || user.email?.charAt(0) || 'U').toUpperCase() }}
                    </AvatarFallback>
                  </Avatar>
                  <span class="text-sm font-medium text-foreground">{{ user.name || user.email }}</span>
                </button>
              </DropdownMenuTrigger>
              <DropdownMenuContent class="w-56" align="end">
                <DropdownMenuLabel>
                  <div class="flex flex-col space-y-1">
                    <p class="text-sm font-medium text-foreground">{{ user.name || 'User' }}</p>
                    <p class="text-xs text-muted-foreground">{{ user.email }}</p>
                  </div>
                </DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuGroup>
                  <DropdownMenuItem as-child>
                    <NuxtLink :to="localePath('/dashboard')" class="flex items-center">
                      <svg class="mr-2 h-4 w-4 text-muted-foreground" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"></path>
                        <circle cx="12" cy="12" r="3"></circle>
                      </svg>
                      {{ t('header.userMenu.personalSettings') }}
                    </NuxtLink>
                  </DropdownMenuItem>
                  <DropdownMenuItem v-if="user.role === 'admin'" as-child>
                    <NuxtLink :to="localePath('/admin')" class="flex items-center">
                      <svg class="mr-2 h-4 w-4 text-muted-foreground" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="M3 3v18h18V3H3zm16 16H5V5h14v14z"/>
                        <path d="M8 8h8m-8 4h8m-8 4h5"/>
                      </svg>
                      {{ t('header.userMenu.adminPanel') }}
                    </NuxtLink>
                  </DropdownMenuItem>
                </DropdownMenuGroup>
                <DropdownMenuSeparator />
                <DropdownMenuItem class="text-destructive" @click="handleSignOut">
                  <svg class="mr-2 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
                    <polyline points="16 17 21 12 16 7"></polyline>
                    <line x1="21" y1="12" x2="9" y2="12"></line>
                  </svg>
                  {{ t('header.auth.signOut') }}
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>

            <div v-else class="flex items-center space-x-2">
              <NuxtLink :to="localePath('/signin')">
                <Button variant="ghost" class="text-sm font-medium">
                  {{ t('header.auth.signIn') }}
                </Button>
              </NuxtLink>
              <NuxtLink :to="localePath('/signup')">
                <Button variant="default" class="text-sm font-medium rounded-full">
                  {{ t('header.auth.getStarted') }}
                </Button>
              </NuxtLink>
            </div>
          </div>
        </div>

        <!-- Mobile menu button -->
        <div class="flex md:hidden">
          <button
            @click="isMenuOpen = !isMenuOpen"
            class="inline-flex items-center justify-center p-2 rounded-md text-muted-foreground hover:text-foreground hover:bg-muted focus:outline-none transition-colors"
          >
            <span class="sr-only">Open main menu</span>
            <!-- Hamburger icon -->
            <svg v-if="!isMenuOpen" class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
            </svg>
            <svg v-else class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      </div>
    </div>

    <!-- Mobile menu -->
    <div v-if="isMenuOpen" class="md:hidden bg-background border-t border-border">
      <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3">
        <NuxtLink 
          :to="localePath('/ai')" 
          class="block px-3 py-2 rounded-md text-base font-medium text-foreground hover:text-foreground hover:bg-muted"
          @click="isMenuOpen = false"
        >
          {{ t('header.navigation.ai') }}
        </NuxtLink>
        <NuxtLink 
          :to="localePath('/premium-features')" 
          class="block px-3 py-2 rounded-md text-base font-medium text-foreground hover:text-foreground hover:bg-muted"
          @click="isMenuOpen = false"
        >
          {{ t('header.navigation.premiumFeatures') }}
        </NuxtLink>
        <NuxtLink 
          :to="localePath('/pricing')" 
          class="block px-3 py-2 rounded-md text-base font-medium text-foreground hover:text-foreground hover:bg-muted"
          @click="isMenuOpen = false"
        >
          {{ t('header.navigation.pricing') }}
        </NuxtLink>
      </div>
      
      <div class="pt-4 pb-3 border-t border-border">
        <div v-if="user" class="px-4 space-y-1">
          <div class="flex items-center px-3">
            <div class="flex-shrink-0">
              <Avatar class="h-10 w-10 border border-border">
                <AvatarImage :src="user.image || ''" :alt="user.name || user.email || 'User'" />
                <AvatarFallback class="bg-muted text-muted-foreground text-sm">
                  {{ (user.name?.charAt(0) || user.email?.charAt(0) || 'U').toUpperCase() }}
                </AvatarFallback>
              </Avatar>
            </div>
            <div class="ml-3">
              <div class="text-base font-medium text-foreground">{{ user.name || 'User' }}</div>
              <div class="text-sm font-medium text-muted-foreground">{{ user.email }}</div>
            </div>
          </div>
          <NuxtLink 
            :to="localePath('/dashboard')" 
            class="block px-3 py-2 rounded-md text-base font-medium text-foreground hover:text-foreground hover:bg-muted"
            @click="isMenuOpen = false"
          >
            {{ t('header.userMenu.personalSettings') }}
          </NuxtLink>
          <NuxtLink 
            v-if="user.role === 'admin'" 
            :to="localePath('/admin')" 
            class="block px-3 py-2 rounded-md text-base font-medium text-foreground hover:text-foreground hover:bg-muted"
            @click="isMenuOpen = false"
          >
            {{ t('header.userMenu.adminPanel') }}
          </NuxtLink>
          <button
            @click="handleSignOut"
            class="block w-full text-left px-3 py-2 rounded-md text-base font-medium text-destructive hover:bg-destructive/10"
          >
            {{ t('header.auth.signOut') }}
          </button>
        </div>
        <div v-else class="flex items-center justify-center space-x-4 px-4 py-2">
          <NuxtLink :to="localePath('/signin')" class="w-1/2" @click="isMenuOpen = false">
            <Button variant="outline" class="w-full text-sm font-medium">
              {{ t('header.auth.signIn') }}
            </Button>
          </NuxtLink>
          <NuxtLink :to="localePath('/signup')" class="w-1/2" @click="isMenuOpen = false">
            <Button variant="default" class="w-full text-sm font-medium rounded-full">
              {{ t('header.auth.getStarted') }}
            </Button>
          </NuxtLink>
        </div>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import { ref } from 'vue'

// Reactive state
const isMenuOpen = ref(false)

// Internationalization - using @nuxtjs/i18n properly
const { t, locale } = useI18n()
const localePath = useLocalePath()
const switchLocalePath = useSwitchLocalePath()

// Authentication
const { user, signOut } = useAuth()

// Available locales for language switcher
const availableLocales = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'zh-CN', name: '中文 (简体)', flag: '🇨🇳' }
]

// Language change handler
const changeLanguage = (targetLocale: string) => {
  // Use Nuxt i18n's switchLocalePath
  const path = switchLocalePath(targetLocale as any)
  if (path) {
    navigateTo(path)
  }
}

// Sign out handler
const handleSignOut = async () => {
  await signOut()
}
</script>
