// apps/next-app/app/[lang]/(root)/dashboard/components/subscription-card.tsx
'use client';

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { 
  CreditCard, 
  CalendarIcon,
  ExternalLink,
  Package
} from "lucide-react";
import Link from "next/link";
import { useTranslation } from "@/hooks/use-translation";
import { toast } from "sonner";
import { config } from "@config";

interface SubscriptionCardProps {
  // Props interface for subscription data if needed
}

export function SubscriptionCard({}: SubscriptionCardProps) {
  const { t, locale: currentLocale } = useTranslation();
  const [subscriptionData, setSubscriptionData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [redirecting, setRedirecting] = useState(false);

  useEffect(() => {
    async function fetchSubscriptionData() {
      try {
        const subscriptionResponse = await fetch('/api/subscription/status');
        if (subscriptionResponse.ok) {
          const data = await subscriptionResponse.json();
          setSubscriptionData(data);
        }
      } catch (error) {
        console.error('Failed to fetch subscription data', error);
      } finally {
        setLoading(false);
      }
    }

    fetchSubscriptionData();
  }, []);

  // 打开客户门户（支持多个支付提供商）
  const openCustomerPortal = async (provider?: string) => {
    try {
      setRedirecting(true);
      const returnUrl = `${window.location.origin}/${currentLocale}/dashboard`;
      
      const response = await fetch('/api/subscription/portal', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ 
          returnUrl,
          provider // 可选：指定支付提供商，如果不指定则自动检测
        }),
      });
      
      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || '无法打开客户门户');
      }
      
      const { url } = await response.json();
      
      // 重定向到客户门户
      window.location.href = url;
    } catch (error) {
      console.error('打开客户门户失败:', error);
      toast.error(t.common.unexpectedError);
      setRedirecting(false);
    }
  };



  // 获取计划名称
  const getPlanName = (planId: string) => {
    const plan = config.payment.plans[planId as keyof typeof config.payment.plans];
    if (!plan) return planId; // 如果找不到计划，则返回 planId
    
    // 使用当前语言的翻译
    if (plan.i18n && plan.i18n[currentLocale]) {
      return plan.i18n[currentLocale].name;
    }
    
    // 如果没有当前语言的翻译，则使用默认名称
    return plan.i18n[currentLocale]?.name || planId;
  };

  // 格式化日期
  const formatDate = (dateString: string | Date) => {
    const date = typeof dateString === 'string' ? new Date(dateString) : dateString;
    return date.toLocaleDateString(currentLocale === 'zh-CN' ? 'zh-CN' : 'en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  };

  // 计算订阅期间已经过去的时间比例
  const calculateProgress = () => {
    if (!subscriptionData?.subscription) return 0;
    
    const start = new Date(subscriptionData.subscription.periodStart).getTime();
    const end = new Date(subscriptionData.subscription.periodEnd).getTime();
    const now = Date.now();
    
    if (now >= end) return 100;
    if (now <= start) return 0;
    
    return Math.floor(((now - start) / (end - start)) * 100);
  };



  if (loading) {
    return (
      <div className="space-y-4">
        <div className="flex items-center justify-center h-40">
          <div className="animate-spin h-10 w-10 border-4 border-primary border-t-transparent rounded-full"></div>
        </div>
      </div>
    );
  }

  // 如果用户没有有效订阅，显示升级选项
  if (!subscriptionData?.hasSubscription && !subscriptionData?.isLifetime) {
    return (
      <div className="space-y-6">
        <Card>
          <CardHeader>
            <CardTitle>{t.subscription.noSubscription.title}</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="mb-4">{t.subscription.noSubscription.description}</p>
            <Button asChild>
              <Link href={`/${currentLocale}/pricing`}>{t.subscription.noSubscription.viewPlans}</Link>
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  const isLifetime = subscriptionData.isLifetime;
  const sub = subscriptionData.subscription;
  const planId = sub?.planId || '';

  return (
    <Card>
      <CardHeader>
        <CardTitle>{t.subscription.title}</CardTitle>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* 订阅概览部分 */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <Package className="h-5 w-5 mr-2 text-primary" />
              <span className="font-medium">{t.subscription.overview.planType}</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="font-medium text-primary">
                {isLifetime ? t.dashboard.subscription.status.lifetime : getPlanName(planId)}
              </span>
              {!isLifetime && sub && (
                <span className="px-2 py-1 rounded-full border text-xs">
                  {sub.paymentType === 'recurring' 
                    ? t.dashboard.subscription.paymentType.recurring 
                    : t.dashboard.subscription.paymentType.oneTime}
                </span>
              )}
            </div>
          </div>
          
          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <CreditCard className="h-5 w-5 mr-2 text-primary" />
              <span className="font-medium">{t.subscription.overview.status}</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="px-2 py-1 rounded-full bg-primary text-primary-foreground text-xs font-medium">
                {t.subscription.overview.active}
              </span>
              {sub?.cancelAtPeriodEnd && (
                <span className="px-2 py-1 rounded-full  bg-accent text-xs">
                  {t.dashboard.subscription.status.cancelAtPeriodEnd}
                </span>
              )}
            </div>
          </div>
          
          {!isLifetime && sub && (
            <>
              <div className="flex items-center justify-between">
                <div className="flex items-center">
                  <CalendarIcon className="h-5 w-5 mr-2 text-primary" />
                  <span className="font-medium">{t.subscription.overview.startDate}</span>
                </div>
                <span>{formatDate(sub.periodStart)}</span>
              </div>
              
              <div className="flex items-center justify-between">
                <div className="flex items-center">
                  <CalendarIcon className="h-5 w-5 mr-2 text-primary" />
                  <span className="font-medium">{t.subscription.overview.endDate}</span>
                </div>
                <span>{formatDate(sub.periodEnd)}</span>
              </div>
              
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="font-medium">{t.subscription.overview.progress}</span>
                  <span>{calculateProgress()}%</span>
                </div>
                <Progress value={calculateProgress()} className="h-2" />
              </div>
            </>
          )}
        </div>

        {/* 分割线 */}
        {/* 只有Stripe和Creem用户才显示管理按钮，微信支付用户没有客户门户 */}
        {(sub?.stripeCustomerId || sub?.creemCustomerId) && (
          <div className="border-t pt-6">
            <h3 className="text-lg font-medium mb-4">{t.subscription.management.title}</h3>
            <div className="rounded-lg border p-4">
              <p className="text-sm text-muted-foreground mb-4">
                {t.subscription.management.description}
              </p>
              <div className="flex gap-3">

                  <Button 
                    variant="default" 
                    className="flex items-center gap-1"
                    onClick={() => openCustomerPortal()}
                    disabled={redirecting}
                  >
                    <ExternalLink className="h-4 w-4" />
                    {redirecting ? t.subscription.management.redirecting : t.subscription.management.manageSubscription}
                  </Button>
              </div>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

// apps/nuxt-app/components/SubscriptionCard.vue
<script setup lang="ts">
import { 
  CreditCard, 
  CalendarIcon,
  ExternalLink,
  Package
} from 'lucide-vue-next'

const { t, locale } = useI18n()
const localePath = useLocalePath()

// Subscription data state
const subscriptionData = ref<any>(null)
const loading = ref(true)
const redirecting = ref(false)

/**
 * Fetch subscription data from API
 */
const fetchSubscriptionData = async () => {
  try {
    const data = await $fetch('/api/subscription/status')
    subscriptionData.value = data
  } catch (error) {
    console.error('Failed to fetch subscription data', error)
  } finally {
    loading.value = false
  }
}

/**
 * Open customer portal (auto-detects provider)
 */
const openCustomerPortal = async (provider?: string) => {
  try {
    redirecting.value = true
    const returnUrl = `${window.location.origin}/dashboard`
    
    const { url } = await $fetch('/api/subscription/portal', {
      method: 'POST',
      body: { 
        returnUrl,
        provider // 可选：指定支付提供商，如果不指定则自动检测
      }
    })
    
    // 重定向到客户门户
    window.location.href = url
  } catch (error) {
    console.error('打开客户门户失败:', error)
    // 显示错误提示
    redirecting.value = false
  }
}

/**
 * Get plan name from config
 */
const getPlanName = (planId: string) => {
  // This would need to be imported from your config
  // For now, return the planId as fallback
  return planId
}

/**
 * Format date according to user locale
 */
const formatDate = (dateString: string | Date) => {
  const date = typeof dateString === 'string' ? new Date(dateString) : dateString
  const currentLocale = locale.value
  return date.toLocaleDateString(currentLocale === 'zh-CN' ? 'zh-CN' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })
}

/**
 * Calculate subscription progress percentage
 */
const calculateProgress = () => {
  if (!subscriptionData.value?.subscription) return 0
  
  const start = new Date(subscriptionData.value.subscription.periodStart).getTime()
  const end = new Date(subscriptionData.value.subscription.periodEnd).getTime()
  const now = Date.now()
  
  if (now >= end) return 100
  if (now <= start) return 0
  
  return Math.floor(((now - start) / (end - start)) * 100)
}

// Computed properties
const isLifetime = computed(() => subscriptionData.value?.isLifetime)
const sub = computed(() => subscriptionData.value?.subscription)
const planId = computed(() => sub.value?.planId || '')

// Fetch data when component mounts
onMounted(() => {
  fetchSubscriptionData()
})
</script>

<template>
  <!-- Loading state -->
  <div v-if="loading" class="space-y-4">
    <div class="flex items-center justify-center h-40">
      <div class="animate-spin h-10 w-10 border-4 border-primary border-t-transparent rounded-full"></div>
    </div>
  </div>

  <!-- No subscription state -->
  <div v-else-if="!subscriptionData?.hasSubscription && !subscriptionData?.isLifetime" class="space-y-6">
    <Card>
      <CardHeader>
        <CardTitle>{{ t('subscription.noSubscription.title') }}</CardTitle>
      </CardHeader>
      <CardContent>
        <p class="mb-4">{{ t('subscription.noSubscription.description') }}</p>
        <Button :as-child="true">
          <NuxtLink :to="localePath('/pricing')">{{ t('subscription.noSubscription.viewPlans') }}</NuxtLink>
        </Button>
      </CardContent>
    </Card>
  </div>

  <!-- Subscription details -->
  <Card v-else>
    <CardHeader>
      <CardTitle>{{ t('subscription.title') }}</CardTitle>
    </CardHeader>
    <CardContent class="space-y-6">
      <!-- 订阅概览部分 -->
      <div class="space-y-4">
        <div class="flex items-center justify-between">
          <div class="flex items-center">
            <Package class="h-5 w-5 mr-2 text-primary" />
            <span class="font-medium">{{ t('subscription.overview.planType') }}</span>
          </div>
          <div class="flex items-center gap-2">
            <span class="font-medium text-primary">
              {{ isLifetime ? t('dashboard.subscription.status.lifetime') : getPlanName(planId) }}
            </span>
            <span 
              v-if="!isLifetime && sub" 
              class="px-2 py-1 rounded-full border text-xs"
            >
              {{ sub.paymentType === 'recurring' 
                ? t('dashboard.subscription.paymentType.recurring') 
                : t('dashboard.subscription.paymentType.oneTime') }}
            </span>
          </div>
        </div>
        
        <div class="flex items-center justify-between">
          <div class="flex items-center">
            <CreditCard class="h-5 w-5 mr-2 text-primary" />
            <span class="font-medium">{{ t('subscription.overview.status') }}</span>
          </div>
          <div class="flex items-center gap-2">
            <span class="px-2 py-1 rounded-full bg-primary text-primary-foreground text-xs font-medium">
              {{ t('subscription.overview.active') }}
            </span>
            <span v-if="sub?.cancelAtPeriodEnd" class="px-2 py-1 rounded-full bg-accent text-xs">
              {{ t('dashboard.subscription.status.cancelAtPeriodEnd') }}
            </span>
          </div>
        </div>
        
        <template v-if="!isLifetime && sub">
          <div class="flex items-center justify-between">
            <div class="flex items-center">
              <CalendarIcon class="h-5 w-5 mr-2 text-primary" />
              <span class="font-medium">{{ t('subscription.overview.startDate') }}</span>
            </div>
            <span>{{ formatDate(sub.periodStart) }}</span>
          </div>
          
          <div class="flex items-center justify-between">
            <div class="flex items-center">
              <CalendarIcon class="h-5 w-5 mr-2 text-primary" />
              <span class="font-medium">{{ t('subscription.overview.endDate') }}</span>
            </div>
            <span>{{ formatDate(sub.periodEnd) }}</span>
          </div>
          
          <div class="space-y-2">
            <div class="flex items-center justify-between">
              <span class="font-medium">{{ t('subscription.overview.progress') }}</span>
              <span>{{ calculateProgress() }}%</span>
            </div>
            <Progress :model-value="calculateProgress()" class="h-2" />
          </div>
        </template>
      </div>

      <!-- 分割线 -->
      <div class="border-t pt-6" v-if="sub?.stripeCustomerId || sub?.creemCustomerId">
        <h3 class="text-lg font-medium mb-4">{{ t('subscription.management.title') }}</h3>
        <div class="rounded-lg border p-4">
          <p class="text-sm text-muted-foreground mb-4">
            {{ t('subscription.management.description') }}
          </p>
          <div class="flex gap-3">
            <!-- 只有Stripe和Creem用户才显示管理按钮，微信支付用户没有客户门户 -->
            <Button 
              variant="default" 
              class="flex items-center gap-1"
              @click="openCustomerPortal()"
              :disabled="redirecting"
            >
              <ExternalLink class="h-4 w-4" />
              {{ redirecting ? t('subscription.management.redirecting') : t('subscription.management.manageSubscription') }}
            </Button>
          </div>
        </div>
      </div>
    </CardContent>
  </Card>
</template>
